# Generated by Django 5.2.1 on 2025-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FalsaPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(help_text='Ingresa la función en términos de x, por ejemplo: x**3 - x - 2', max_length=255)),
                ('x0', models.FloatField(help_text='Extremo izquierdo del intervalo')),
                ('x1', models.FloatField(help_text='Extremo derecho del intervalo')),
                ('tolerancia', models.FloatField(default=0.0001, help_text='Tolerancia del método')),
                ('max_iteraciones', models.IntegerField(default=100, help_text='Número máximo de iteraciones')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
