# Generated by Django 5.2.1 on 2025-05-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='falsaposicion',
            options={'ordering': ['-creado'], 'verbose_name': 'Cálculo Falsa Posición', 'verbose_name_plural': 'Cálculos Falsa Posición'},
        ),
        migrations.AddField(
            model_name='falsaposicion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
