# Generated by Django 5.2.1 on 2025-05-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0002_alter_falsaposicion_options_falsaposicion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='falsaposicion',
            name='grafico_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
