# Generated by Django 5.2.1 on 2025-05-18 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos', '0003_falsaposicion_grafico_base64'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaussEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz_a', models.TextField(help_text='Matriz A como lista de listas')),
                ('vector_b', models.TextField(help_text='Vector b como lista')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('grafico_base64', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo Gauss',
                'verbose_name_plural': 'Cálculos Gauss',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='GaussJordan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz_a', models.TextField(help_text='Matriz A como lista de listas')),
                ('vector_b', models.TextField(help_text='Vector b como lista')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('grafico_base64', models.TextField(blank=True, null=True)),
                ('matriz_transformada', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cálculo Gauss-Jordan',
                'verbose_name_plural': 'Cálculos Gauss-Jordan',
                'ordering': ['-creado'],
            },
        ),
    ]
